# Generated by Django 3.0.6 on 2020-10-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='taken_apt_test',
            field=models.BooleanField(default=True),
        ),
    ]
