# Generated by Django 3.0.6 on 2020-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201009_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='taken_apt_test',
            field=models.BooleanField(default=False),
        ),
    ]
