# Generated by Django 3.0.6 on 2020-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchoice',
            name='is_answer',
            field=models.BooleanField(default=True),
        ),
    ]
