# Generated by Django 3.0.6 on 2020-12-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_auto_20201206_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testchoice',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
