# Generated by Django 3.0.6 on 2020-12-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_auto_20201207_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_result', models.CharField(max_length=500)),
                ('bad_result', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personality.PersonalityType')),
            ],
        ),
    ]
