# Generated by Django 3.0.6 on 2020-12-06 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
                ('phone', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.Templates'),
        ),
        migrations.CreateModel(
            name='PersonalDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(blank=True, max_length=255)),
                ('about', models.TextField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('introduction', models.TextField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('course', models.CharField(blank=True, max_length=255)),
                ('startingDate', models.CharField(blank=True, max_length=255)),
                ('endingDate', models.CharField(blank=True, max_length=255)),
                ('experienceInfo', models.TextField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('course', models.BooleanField(blank=True, default=0)),
                ('edate1', models.CharField(blank=True, max_length=255)),
                ('edate2', models.CharField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(blank=True, max_length=255)),
                ('certificateDate', models.CharField(blank=True, max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
    ]
