# Generated by Django 3.0.6 on 2020-06-23 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=255, unique=True)),
                ('lastname', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('dob', models.DateField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, unique=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, unique=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('course', models.CharField(max_length=255, unique=True)),
                ('startingDate', models.DateField(max_length=255, unique=True)),
                ('endingDate', models.DateField(max_length=255, unique=True)),
                ('experienceInfo', models.TextField(max_length=255, unique=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=255, unique=True)),
                ('institution', models.CharField(max_length=100, unique=True)),
                ('course', models.BooleanField(default=0)),
                ('edate1', models.DateField(max_length=255, unique=True)),
                ('edate2', models.DateField(max_length=255, unique=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=255, unique=True)),
                ('certificateDate', models.DateField(max_length=255, unique=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=255, unique=True)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
    ]
