# Generated by Django 3.0.6 on 2021-05-03 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('full_Name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=30)),
                ('subject', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
