# Generated by Django 3.0.6 on 2020-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200623_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='country',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='state',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='lastname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middlename',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
    ]
