# Generated by Django 3.0.6 on 2020-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200625_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificateDate',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='edate1',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='edate2',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='program',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='course',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='endingDate',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='experienceInfo',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='startingDate',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
