# Generated by Django 3.0.6 on 2020-07-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200701_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='firstname',
            new_name='personalinfo',
        ),
    ]
