# Generated by Django 3.0.6 on 2020-08-04 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_personalinfo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificateDate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='edate1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='edate2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='endingDate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='startingDate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='dob',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='PersonalDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=255)),
                ('about', models.TextField(max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('introduction', models.TextField(max_length=255)),
                ('personalinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.PersonalInfo')),
            ],
        ),
    ]
