# Generated by Django 3.0.6 on 2020-08-05 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200805_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='middlename',
            field=models.CharField(max_length=255),
        ),
    ]
