# Generated by Django 3.0.6 on 2020-08-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20200805_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
