# Generated by Django 3.0.6 on 2020-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20200805_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalinfo',
            name='course',
            field=models.BooleanField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='edate1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='edate2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='educationalinfo',
            name='program',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='endingDate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='experienceInfo',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='startingDate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='experienceinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='others',
            name='introduction',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='others',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldescription',
            name='Job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldescription',
            name='about',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='middlename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
